### ISSUE TITLE
feedback

### ISSUE THREAD

**Issue by dvberkel** [HAN-ASD-DT/trees-assignment-dcswitzer#2]
looks good.

Good job implementing the `repeat` function. You can also find it in the [core](https://package.elm-lang.org/packages/elm/core/latest/List#repeat) library

**Comment by dcswitzer** [comment]
I was wondering why you would say that i can also find it in the core library. But if i understand it the right way it is possible to use functions from the core without implementing itself, like list.repeat, like you showed us in the lecture from 06-11 with the set.foldl. Dont exactly know if i'm right, but this is something i have to try. I will do this later, for now i will focus on other assignments.
